[app]
name = "in4s"
description = "slide on your block like danny glover with a lethal weapon"
browsers = ["> 10%", "not ie < 11"]


[intl]
defaultLanguage = "en"
supportedLanguages = ["en", "zh", "es", "de", "hi", "ar"]

[services.auth]
domain = ""
clientID = ""
redirectUri = ""
audience = ""
responseType = "token id_token"
scope = "openid"

[services.user]
name = "dsd"
