# Build Settings
# --------------
#
#

[targets]
node = "current"
browsers = [
  "> 10%",
  "not ie < 11"
]

[stages.development]
url = "http://localhost:4200"
enableDevtools = false
enableDebugger = false
enableSourcemaps = false

[stages.staging]
url = "http://localhost:4200"
enableDevtools = true
enableDebugger = true
enableSourcemaps = true

[stages.production]
url = "http://localhost:4200"
enableDevtools = false
enableDebugger = false
enableSourcemaps = true
